# Generated by Django 2.2.7 on 2020-05-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frequency',
            new_name='Topic',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Negativity',
        ),
        migrations.DeleteModel(
            name='TimeSeries',
        ),
    ]
