# Generated by Django 2.2.7 on 2020-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_disclaimer_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disclaimer',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='explanation',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='disclaimer',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='explanation',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
